from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import subprocess

from setuptools import build_meta as _build_meta

BUILD_INFO_MODULE = Path(__file__).resolve().parent / "src" / "onnx2c" / "_build_info.py"


def _write_build_info() -> None:
    build_date = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    git_version = _read_git_version()
    BUILD_INFO_MODULE.write_text(
        """"""Auto-generated by build backend. Do not edit."""""\n"
        f"BUILD_DATE = {build_date!r}\n",
        f"GIT_VERSION = {git_version!r}\n",
        encoding="utf-8",
    )


def _read_git_version() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return result.stdout.strip() or "unknown"


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    _write_build_info()
    return _build_meta.build_wheel(
        wheel_directory,
        config_settings=config_settings,
        metadata_directory=metadata_directory,
    )


def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
    _write_build_info()
    return _build_meta.build_editable(
        wheel_directory,
        config_settings=config_settings,
        metadata_directory=metadata_directory,
    )


def build_sdist(sdist_directory, config_settings=None):
    return _build_meta.build_sdist(sdist_directory, config_settings=config_settings)


def get_requires_for_build_wheel(config_settings=None):
    return _build_meta.get_requires_for_build_wheel(config_settings=config_settings)


def get_requires_for_build_editable(config_settings=None):
    return _build_meta.get_requires_for_build_editable(config_settings=config_settings)


def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None):
    return _build_meta.prepare_metadata_for_build_wheel(
        metadata_directory, config_settings=config_settings
    )


def prepare_metadata_for_build_editable(metadata_directory, config_settings=None):
    return _build_meta.prepare_metadata_for_build_editable(
        metadata_directory, config_settings=config_settings
    )
