/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 878ae8cb7dabee373c687a1ce8e67efb3365cc50d2e3f2a490f9a4d53d53a929
 * Model name: model
 * Graph name: add_init_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

static const float weight[2][3] = {
    0.100000001f, 0.200000003f, 0.300000012f, 0.400000006f, 0.5f, 0.600000024f
};

/*
 * Node 0:
 * OpType: Add
 * Inputs: in0, weight
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float in0[2][3], const float weight[2][3], float out[2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = in0[i0][i1] + weight[i0][i1];
        }
    }
}

void model(const float in0[2][3], float out[2][3]) {
    model_op0(in0, weight, out);
}
