// Generated by emx-onnx2c (MVP)
#include <stddef.h>

void model_op0(const float* a, const float* b, float* out) {
    for (size_t i = 0; i < 6; ++i) {
        out[i] = a[i] + b[i];
    }
}

void model(const float* a, const float* b, float* out) {
    model_op0(a, b, out);
}
