/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 878ae8cb7dabee373c687a1ce8e67efb3365cc50d2e3f2a490f9a4d53d53a929
 * Model name: model
 * Graph name: add_init_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

/*
 * Weight 1:
 * Name: weight1_weight
 * Shape: (2, 3)
 * Elements: 6
 * Dtype: float
 */
static const float weight1_weight[2][3] = {
    0.100000001f, 0.200000003f, 0.300000012f, 0.400000006f, 0.5f, 0.600000024f
};

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

/*
 * Node 0:
 * OpType: Add
 * Name: n/a
 * Inputs: in0, weight
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_add(const float input0[restrict 2][3], const float input1[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_add(input0[i0][i1], input1[i0][i1]);
        }
    }
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_add(in0, weight1_weight, out);
}
