/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 7f36b3cd457cc502c87a14a68d8689976648969788a649d24b2b27621b57257c
 * Model name: model
 * Graph name: add_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

/*
 * Node 0:
 * OpType: Add
 * Name: n/a
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_add(const float input0[restrict 2][3][4], const float input1[restrict 2][3][4], float output[restrict 2][3][4]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            for (size_t i2 = 0; i2 < 4; ++i2) {
                output[i0][i1][i2] = ref_scalar_f32_add(input0[i0][i1][i2], input1[i0][i1][i2]);
            }
        }
    }
}

void model(const float a[restrict 2][3][4], const float b[restrict 2][3][4], float out[restrict 2][3][4]) {
    node0_add(a, b, out);
}
