/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 7f36b3cd457cc502c87a14a68d8689976648969788a649d24b2b27621b57257c
 * Model name: model
 * Graph name: add_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: Add
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float a[2][3][4], const float b[2][3][4], float out[2][3][4]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            for (size_t i2 = 0; i2 < 4; ++i2) {
                out[i0][i1][i2] = a[i0][i1][i2] + b[i0][i1][i2];
            }
        }
    }
}

void model(const float a[2][3][4], const float b[2][3][4], float out[2][3][4]) {
    model_op0(a, b, out);
}
