/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 8f95375285b39b185f94504c4e73b7144b27843901db46fd29fa71f6738e21ee
 * Model name: dynamic_dims_model
 * Graph name: relu_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Relu
 * Name: n/a
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Relu(int N, int C, const float input0[restrict N][C], float output[restrict N][C]) {
    for (size_t i0 = 0; i0 < N; ++i0) {
        for (size_t i1 = 0; i1 < C; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

void dynamic_dims_model(int N, int C, const float x[restrict N][C], float out[restrict N][C]) {
    node0_Relu(N, C, x, out);
}
