/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 8f95375285b39b185f94504c4e73b7144b27843901db46fd29fa71f6738e21ee
 * Model name: dynamic_dims_model
 * Graph name: relu_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Relu
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void dynamic_dims_model_op0(const float x[restrict 1][1], float out[restrict 1][1]) {
    for (size_t i0 = 0; i0 < 1; ++i0) {
        for (size_t i1 = 0; i1 < 1; ++i1) {
            out[i0][i1] = ref_scalar_f32_relu(x[i0][i1]);
        }
    }
}

void dynamic_dims_model(int dim1, int dim2, int dim3, int dim4, const float x[restrict dim1][dim2], float out[restrict dim3][dim4]) {
    dynamic_dims_model_op0(x, out);
}
