/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 2f0e4324e14da66040e7ca5deeee256dd77ed24c463ab98099791bb1de560c76
 * Model name: large_temp_static_model
 * Graph name: large_temp_graph
 * Inputs: 2 Outputs: 1 Nodes: 2 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Add
 * Name: n/a
 * Inputs: a, b
 * Outputs: tmp
 * Attrs: n/a
 */
static inline void node0_add(const float input0[restrict 1][257], const float input1[restrict 1][257], float output[restrict 1][257]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 257; ++i1) {
            output[i0][i1] = ref_scalar_f32_add(input0[0][i1], input1[0][i1]);
        }
    }
}

/*
 * Node 1:
 * OpType: Relu
 * Name: n/a
 * Inputs: tmp
 * Outputs: out
 * Attrs: n/a
 */
static inline void node1_relu(const float input0[restrict 1][257], float output[restrict 1][257]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 257; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

void large_temp_static_model(const float a[restrict 1][257], const float b[restrict 1][257], float out[restrict 1][257]) {
    static float tmp0_tmp[1][257];
    node0_add(a, b, tmp0_tmp);
    node1_relu(tmp0_tmp, out);
}
