/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): cacaf121665f8f4f8bda3b154f45e8ddb1550c335cda7eb63323efd2693a9e0e
 * Model name: model
 * Graph name: matmul_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: MatMul
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float a[2][3], const float b[3][4], float out[2][4]) {
for (size_t i0 = 0; i0 < 2; ++i0) {
    for (size_t i1 = 0; i1 < 4; ++i1) {
        float acc = 0.0f;
        for (size_t k = 0; k < 3; ++k) {
            acc += a[i0][k] * b[k][i1];
        }
        out[i0][i1] = acc;
}
    }
}

void model(const float a[2][3], const float b[3][4], float out[2][4]) {
    model_op0(a, b, out);
}
