// Generated by emx-onnx2c (MVP)
#include <stddef.h>

void model_op0(const float a[2][3], const float b[3][4], float out[2][4]) {
for (size_t i0 = 0; i0 < 2; ++i0) {
    for (size_t i1 = 0; i1 < 4; ++i1) {
        float acc = 0.0f;
        for (size_t k = 0; k < 3; ++k) {
            acc += a[i0][k] * b[k][i1];
        }
        out[i0][i1] = acc;
}
    }
}

void model(const float a[2][3], const float b[3][4], float out[2][4]) {
    model_op0(a, b, out);
}
