// Generated by emx-onnx2c (MVP)
#include <stddef.h>

void model_op0(const float a[2][3], const float b[3][4], float out[2][4]) {
    for (size_t i = 0; i < 2; ++i) {
        for (size_t j = 0; j < 4; ++j) {
            float acc = 0.0f;
            for (size_t k = 0; k < 3; ++k) {
                acc += a[i][k] * b[k][j];
            }
            out[i][j] = acc;
        }
    }
}

void model(const float a[2][3], const float b[3][4], float out[2][4]) {
    model_op0(a, b, out);
}
