/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 27622e7e26c75734c107bd4492a30b89e08f9ad6c19f0072b6c80e3944ea54f2
 * Model name: model
 * Graph name: mul_add_graph
 * Inputs: 3 Outputs: 1 Nodes: 2 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: Mul
 * Inputs: a, b
 * Outputs: mul_out
 * Attrs: n/a
 */
static inline void model_op0(const float a[restrict 2][3], const float b[restrict 2][3], float tmp[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            tmp[i0][i1] = a[i0][i1] * b[i0][i1];
        }
    }
}

/*
 * Node 1:
 * OpType: Add
 * Inputs: mul_out, c
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op1(const float tmp[restrict 2][3], const float c[restrict 2][3], float out[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = tmp[i0][i1] + c[i0][i1];
        }
    }
}

void model(const float a[restrict 2][3], const float b[restrict 2][3], const float c[restrict 2][3], float out[restrict 2][3]) {
    float tmp[2][3];
    model_op0(a, b, tmp);
    model_op1(tmp, c, out);
}
