/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 9197725352e1899c9988f056545c09f78c03acaef539a8995262e8f9cd3b0671
 * Model name: model
 * Graph name: mul_add_relu_graph
 * Inputs: 3 Outputs: 1 Nodes: 3 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif

static inline float ref_scalar_f32_mul(float a, float b) {
    return a * b;
}

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Mul
 * Name: n/a
 * Inputs: a, b
 * Outputs: mul_out
 * Attrs: n/a
 */
static inline void node0_Mul(const float input0[restrict 2][3], const float input1[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_mul(input0[i0][i1], input1[i0][i1]);
        }
    }
}

/*
 * Node 1:
 * OpType: Add
 * Name: n/a
 * Inputs: mul_out, c
 * Outputs: add_out
 * Attrs: n/a
 */
static inline void node1_Add(const float input0[restrict 2][3], const float input1[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_add(input0[i0][i1], input1[i0][i1]);
        }
    }
}

/*
 * Node 2:
 * OpType: Relu
 * Name: n/a
 * Inputs: add_out
 * Outputs: out
 * Attrs: n/a
 */
static inline void node2_Relu(const float input0[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

void model(const float a[restrict 2][3], const float b[restrict 2][3], const float c[restrict 2][3], float out[restrict 2][3]) {
    float tmp0[2][3];
    float tmp1[2][3];
    node0_Mul(a, b, tmp0);
    node1_Add(tmp0, c, tmp1);
    node2_Relu(tmp1, out);
}
