// Generated by emx-onnx2c (MVP)
#include <stddef.h>

void model_op0(const float* a, const float* b, float* tmp) {
    for (size_t i = 0; i < 6; ++i) {
        tmp[i] = a[i] * b[i];
    }
}

void model_op1(const float* tmp, const float* c, float* out) {
    for (size_t i = 0; i < 6; ++i) {
        out[i] = tmp[i] + c[i];
    }
}

void model(const float* a, const float* b, const float* c, float* out) {
    float tmp[6];
    model_op0(a, b, tmp);
    model_op1(tmp, c, out);
}
