/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 27622e7e26c75734c107bd4492a30b89e08f9ad6c19f0072b6c80e3944ea54f2
 * Model name: model
 * Graph name: mul_add_graph
 * Inputs: 3 Outputs: 1 Nodes: 2 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_mul(float a, float b) {
    return a * b;
}

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

/*
 * Node 0:
 * OpType: Mul
 * Name: n/a
 * Inputs: a, b
 * Outputs: mul_out
 * Attrs: n/a
 */
static inline void node0_mul(const float input0[2][3], const float input1[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_mul(input0[i0][i1], input1[i0][i1]);
        }
    }
}

/*
 * Node 1:
 * OpType: Add
 * Name: n/a
 * Inputs: mul_out, c
 * Outputs: out
 * Attrs: n/a
 */
static inline void node1_add(const float input0[2][3], const float input1[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_add(input0[i0][i1], input1[i0][i1]);
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float a[restrict 2][3], const float b[restrict 2][3], const float c[restrict 2][3], float out[restrict 2][3]) {
    float tmp0_mul_out[2][3];
    node0_mul(a, b, tmp0_mul_out);
    node1_add(tmp0_mul_out, c, out);
}
