/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 51d1c4a61a93ed1bac81511671e007e9c80ecd03a5974733a23f01574010c6d9
 * Model name: model
 * Graph name: mul_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif

static inline float ref_scalar_f32_mul(float a, float b) {
    return a * b;
}

/*
 * Node 0:
 * OpType: Mul
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float a[restrict 2][3], const float b[restrict 2][3], float out[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = ref_scalar_f32_mul(a[i0][i1], b[i0][i1]);
        }
    }
}

void model(const float a[restrict 2][3], const float b[restrict 2][3], float out[restrict 2][3]) {
    model_op0(a, b, out);
}
