/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 9ccb2802c0f63a1d1d9a1945af432d6a93e3606d565c11c95f577d83ff9ae018
 * Model name: model
 * Graph name: average_pool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: AveragePool
 * Name: n/a
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   kernel_shape: [2, 2]
 *   strides: [2, 2]
 */
static inline void node0_AveragePool(const float input0[restrict 1][1][4][4], float output[restrict 1][1][2][2]) {
    for (size_t n = 0; n < 1; ++n) {
        for (size_t c = 0; c < 1; ++c) {
            for (size_t oh = 0; oh < 2; ++oh) {
                for (size_t ow = 0; ow < 2; ++ow) {
                    float acc = 0.0f;
                    size_t count = 0;
                    for (size_t kh = 0; kh < 2; ++kh) {
                        const int ih = (int)(oh * 2 + kh) - 0;
                        if (ih < 0 || ih >= 4) {
                            if (0) {
                                count += 2;
                            }
                            continue;
                        }
                        for (size_t kw = 0; kw < 2; ++kw) {
                            const int iw = (int)(ow * 2 + kw) - 0;
                            if (iw < 0 || iw >= 4) {
                                if (0) {
                                    count += 1;
                                }
                                continue;
                            }
                            acc += input0[n][c][ih][iw];
                            count += 1;
                        }
                    }
                    output[n][c][oh][ow] = count ? acc / (float)count : 0.0f;
                }
            }
        }
    }
}

void model(const float input[restrict 1][1][4][4], float output[restrict 1][1][2][2]) {
    node0_AveragePool(input, output);
}
