/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 9ccb2802c0f63a1d1d9a1945af432d6a93e3606d565c11c95f577d83ff9ae018
 * Model name: model
 * Graph name: average_pool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: AveragePool
 * Name: n/a
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   kernel_shape: [2, 2]
 *   strides: [2, 2]
 */
static inline float node0_averagepool_pairwise_sum(const float *values, idx_t n) {
    if (n < 8) {
        float res = -0.0f;
        for (idx_t i = 0; i < n; ++i) {
            res += values[i];
        }
        return res;
    }
    if (n <= 128) {
        float r[8];
        r[0] = values[0];
        r[1] = values[1];
        r[2] = values[2];
        r[3] = values[3];
        r[4] = values[4];
        r[5] = values[5];
        r[6] = values[6];
        r[7] = values[7];
        idx_t i = 8;
        for (; i < n - (n % 8); i += 8) {
            r[0] += values[i + 0];
            r[1] += values[i + 1];
            r[2] += values[i + 2];
            r[3] += values[i + 3];
            r[4] += values[i + 4];
            r[5] += values[i + 5];
            r[6] += values[i + 6];
            r[7] += values[i + 7];
        }
        float res = ((r[0] + r[1]) + (r[2] + r[3])) + ((r[4] + r[5]) + (r[6] + r[7]));
        for (; i < n; ++i) {
            res += values[i];
        }
        return res;
    }
    idx_t n2 = n / 2;
    n2 -= n2 % 8;
    return node0_averagepool_pairwise_sum(values, n2) + node0_averagepool_pairwise_sum(values + n2, n - n2);
}

static inline void node0_averagepool(const float input0[1][1][4][4], float output[1][1][2][2]) {
    for (idx_t n = 0; n < 1; ++n) {
        for (idx_t c = 0; c < 1; ++c) {
            for (idx_t oh = 0; oh < 2; ++oh) {
                for (idx_t ow = 0; ow < 2; ++ow) {
                    float window_vals[4];
                    idx_t value_count = 0;
                    idx_t count = 0;
                    for (idx_t kh = 0; kh < 2; ++kh) {
                        const idx_t ih = oh * 2 + kh * 1 - 0;
                        if (ih < 0 || ih >= 4) {
                            if (0 && ih < 4 + 0) {
                                count += 2;
                            }
                        } else {
                            for (idx_t kw = 0; kw < 2; ++kw) {
                                const idx_t iw = ow * 2 + kw * 1 - 0;
                                if (iw < 0 || iw >= 4) {
                                    if (0 && iw < 4 + 0) {
                                        count += 1;
                                    }
                                } else {
                                    window_vals[value_count++] = input0[n][c][ih][iw];
                                    count += 1;
                                }
                            }
                        }
                    }
                    output[n][c][oh][ow] = count ? (float)(node0_averagepool_pairwise_sum(window_vals, value_count) / (float)count) : 0.0f;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 1][1][4][4], float output[restrict 1][1][2][2]) {
    node0_averagepool(input, output);
}
