/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): e2684cbc2ed66c90eeb78805f0316272311f2cfbfbdf5ced3dc4ea3e604f7cbb
 * Model name: model
 * Graph name: argmax_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Node 0:
 * OpType: ArgMax
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   axis: 1
 *   keepdims: 1
 *   select_last_index: 0
 */
static inline void model_op0(const float input0[restrict 2][3][4], int64_t output[restrict 2][1][4]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 1; ++i1) {
            for (size_t i2 = 0; i2 < 4; ++i2) {
                float best = input0[i0][0][i2];
                int64_t best_index = 0;
                for (size_t r0 = 1; r0 < 3; ++r0) {
                    float candidate = input0[i0][r0][i2];
                    if (candidate > best) {
                        best = candidate;
                        best_index = (int64_t)r0;
                    }
                }
                output[i0][i1][i2] = best_index;
            }
        }
    }
}

void model(const float input[restrict 2][3][4], int64_t output[restrict 2][1][4]) {
    model_op0(input, output);
}
