/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 9ccb2802c0f63a1d1d9a1945af432d6a93e3606d565c11c95f577d83ff9ae018
 * Model name: model
 * Graph name: average_pool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: AveragePool
 * Name: n/a
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   kernel_shape: [2, 2]
 *   strides: [2, 2]
 */
static inline void node0_averagepool(const float input0[1][1][4][4], float output[1][1][2][2]) {
    for (idx_t n = 0; n < 1; ++n) {
        for (idx_t c = 0; c < 1; ++c) {
            for (idx_t oh = 0; oh < 2; ++oh) {
                for (idx_t ow = 0; ow < 2; ++ow) {
                    float values[4];
                    idx_t count = 0;
                    for (idx_t kh = 0; kh < 2; ++kh) {
                        const idx_t ih = oh * 2 + kh * 1 - 0;
                        for (idx_t kw = 0; kw < 2; ++kw) {
                            const idx_t iw = ow * 2 + kw * 1 - 0;
                            if (ih >= 0 && ih < 4 && iw >= 0 && iw < 4) {
                                values[count++] = input0[n][c][ih][iw];
                            } else if (0) {
                                values[count++] = 0.0f;
                            }
                        }
                    }
                    const idx_t denom = 0
                    ? 4
                    : count;
                    float acc = 0.0f;
                    if (count > 0) {
                        idx_t reduce_count = count;
                        while (reduce_count > 1) {
                            idx_t next = 0;
                            for (idx_t i = 0; i + 1 < reduce_count; i += 2) {
                                values[next++] = values[i] + values[i + 1];
                            }
                            if (reduce_count % 2) {
                                values[next++] = values[reduce_count - 1];
                            }
                            reduce_count = next;
                        }
                        acc = values[0];
                    }
                    output[n][c][oh][ow] = denom ? acc / (float)denom : 0.0f;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 1][1][4][4], float output[restrict 1][1][2][2]) {
    node0_averagepool(input, output);
}
