/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): ea374829ef5f717d4e0f3a5368f05a822acbdc8dc140fc9fb7511c3cf1c0d5b0
 * Model name: model
 * Graph name: batchnorm_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 4
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Weight 1:
 * Name: weight1_scale
 * Shape: (3,)
 * Elements: 3
 * Dtype: float
 */
static const float weight1_scale[3] = {
    1.0f, 1.5f, -0.5f
};

/*
 * Weight 2:
 * Name: weight2_bias
 * Shape: (3,)
 * Elements: 3
 * Dtype: float
 */
static const float weight2_bias[3] = {
    0.0f, 0.100000001f, -0.200000003f
};

/*
 * Weight 3:
 * Name: weight3_mean
 * Shape: (3,)
 * Elements: 3
 * Dtype: float
 */
static const float weight3_mean[3] = {
    0.5f, -0.5f, 1.0f
};

/*
 * Weight 4:
 * Name: weight4_var
 * Shape: (3,)
 * Elements: 3
 * Dtype: float
 */
static const float weight4_var[3] = {
    0.25f, 0.5f, 1.5f
};

/*
 * Node 0:
 * OpType: BatchNormalization
 * Name: n/a
 * Inputs: in0, scale, bias, mean, var
 * Outputs: out
 * Attrs:
 *   epsilon: 9.999999747378752e-06
 */
static inline void node0_batchnormalization(const float input0[restrict 2][3][2][2], const float scale[restrict 3], const float bias[restrict 3], const float mean[restrict 3], const float variance[restrict 3], float output[restrict 2][3][2][2]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            for (size_t i2 = 0; i2 < 2; ++i2) {
                for (size_t i3 = 0; i3 < 2; ++i3) {
                    size_t c = i1;
                    float denom = sqrtf(variance[c] + 9.99999975e-06f);
                    output[i0][i1][i2][i3] = (input0[i0][i1][i2][i3] - mean[c]) / denom * scale[c] + bias[c];
                }
            }
        }
    }
}

void model(const float in0[restrict 2][3][2][2], float out[restrict 2][3][2][2]) {
    node0_batchnormalization(in0, weight1_scale, weight2_bias, weight3_mean, weight4_var, out);
}
