/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 42b39b2bbb1872770d786fabe40630e192bc73fcf1c2814ffd62eda59c66ff79
 * Model name: model
 * Graph name: mul_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif

static inline float ref_scalar_f32_mul(float a, float b) {
    return a * b;
}

/*
 * Node 0:
 * OpType: Mul
 * Name: n/a
 * Inputs: in0, in1
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Mul(const float input0[restrict 2][3], const float input1[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_mul(input0[i0][i1], input1[i0][i1]);
        }
    }
}

void model(const float in0[restrict 2][3], const float in1[restrict 2][3], float out[restrict 2][3]) {
    node0_Mul(in0, in1, out);
}
