/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 0077169ef232cc1c63689c66feb370fdd1ebd9a0fb79c7616c52af22eb4e7920
 * Model name: model
 * Graph name: clip_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Weight 1:
 * Name: min
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
static const float min[1] = {
    0.0f
};

/*
 * Weight 2:
 * Name: max
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
static const float max[1] = {
    6.0f
};

/*
 * Node 0:
 * OpType: Clip
 * Name: n/a
 * Inputs: input, min, max
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_clip(const float input0[restrict 2][3], const float input_min[restrict 1], const float input_max[restrict 1], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            float value = input0[i0][i1];
            if (value < input_min[0]) {
                value = input_min[0];
            }
            if (value > input_max[0]) {
                value = input_max[0];
            }
            output[i0][i1] = value;
        }
    }
}

void model(const float input[restrict 2][3], float output[restrict 2][3]) {
    node0_clip(input, min, max, output);
}
