/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): c3e47b6b0afa822e9997d7043d38f74e566c50f2cc0af41969b5739f4f73a96c
 * Model name: model
 * Graph name: conv_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

static const float weight[1][1][3][3] = {
    0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f,
    8.0f
};

static const float bias[1] = {
    0.25f
};

/*
 * Node 0:
 * OpType: Conv
 * Name: n/a
 * Inputs: in0, weight, bias
 * Outputs: out
 * Attrs:
 *   pads: [1, 1, 1, 1]
 *   strides: [1, 1]
 */
static inline void node0_Conv(const float input0[restrict 1][1][4][4], const float weights[restrict 1][1][3][3], const float bias[restrict 1], float output[restrict 1][1][4][4]) {
    for (size_t n = 0; n < 1; ++n) {
        for (size_t g = 0; g < 1; ++g) {
            for (size_t oc = 0; oc < 1; ++oc) {
                const size_t oc_global = g * 1 + oc;
                for (size_t od0 = 0; od0 < 4; ++od0) {
                    for (size_t od1 = 0; od1 < 4; ++od1) {
                        float acc = bias[oc_global];
                        for (size_t ic = 0; ic < 1; ++ic) {
                            const size_t ic_global = g * 1 + ic;
                            for (size_t kd0 = 0; kd0 < 3; ++kd0) {
                                for (size_t kd1 = 0; kd1 < 3; ++kd1) {
                                    const int id0 = (int)(od0 * 1 + kd0 * 1) - 1;
                                    const int id1 = (int)(od1 * 1 + kd1 * 1) - 1;
                                    if (id0 < 0 || id0 >= 4 || id1 < 0 || id1 >= 4) {
                                        continue;
                                    }
                                    acc += input0[n][ic_global][id0][id1] * weights[oc_global][ic][kd0][kd1];
                                }
                            }
                        }
                        output[n][oc_global][od0][od1] = acc;
                    }
                }
            }
        }
    }
}

void model(const float in0[restrict 1][1][4][4], float out[restrict 1][1][4][4]) {
    node0_Conv(in0, weight, bias, out);
}
