/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 353e88e68b0497f06ef44dbdb6b9052fecb358f3370f1af0bfef06167d405dbc
 * Model name: model
 * Graph name: concat_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <string.h>

/*
 * Node 0:
 * OpType: Concat
 * Inputs: in0, in1
 * Outputs: out
 * Attrs:
 *   axis: 2
 */
static inline void model_op0(const float in0[restrict 1][2][3], const float in1[restrict 1][2][1], float out[restrict 1][2][4]) {
    const void *inputs[] = { in0, in1 };
    const size_t axis_sizes[] = { 3, 1 };
    size_t concat_axis = 0;
    for (size_t idx = 0; idx < 2; ++idx) {
        concat_axis += axis_sizes[idx];
    }
    if (concat_axis == 0) {
        return;
    }
    for (size_t outer_idx = 0; outer_idx < 2; ++outer_idx) {
        size_t output_offset = outer_idx * concat_axis * 1;
        size_t axis_offset = 0;
        for (size_t input_idx = 0; input_idx < 2; ++input_idx) {
            size_t axis = axis_sizes[input_idx];
            size_t copy_elems = axis * 1;
            const unsigned char *input_bytes =
            (const unsigned char *)inputs[input_idx];
            size_t input_offset = outer_idx * copy_elems;
            memcpy(
            ((unsigned char *)out) + (output_offset + axis_offset) * sizeof(float),
            input_bytes + input_offset * sizeof(float),
            copy_elems * sizeof(float)
            );
            axis_offset += copy_elems;
        }
    }
}

void model(const float in0[restrict 1][2][3], const float in1[restrict 1][2][1], float out[restrict 1][2][4]) {
    model_op0(in0, in1, out);
}
