/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 0077169ef232cc1c63689c66feb370fdd1ebd9a0fb79c7616c52af22eb4e7920
 * Model name: model
 * Graph name: clip_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

static const float min[1] = {
    0.0f
};

static const float max[1] = {
    6.0f
};

/*
 * Node 0:
 * OpType: Clip
 * Inputs: input, min, max
 * Outputs: output
 * Attrs: n/a
 */
static inline void model_op0(const float input[restrict 2][3], const float min[restrict 1], const float max[restrict 1], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            float value = input[i0][i1];
            if (value < min[0]) {
                value = min[0];
            }
            if (value > max[0]) {
                value = max[0];
            }
            output[i0][i1] = value;
        }
    }
}

void model(const float input[restrict 2][3], float output[restrict 2][3]) {
    model_op0(input, min, max, output);
}
