/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 3213c0f229fe539f85afde789800b0eb048cea0d577dfe88e61972100a0ab890
 * Model name: model
 * Graph name: cast_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Node 0:
 * OpType: Cast
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   to: 6
 */
static inline void model_op0(const float input0[restrict 2][3], int32_t output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = (int32_t)input0[i0][i1];
        }
    }
}

void model(const float in0[restrict 2][3], int32_t out[restrict 2][3]) {
    model_op0(in0, out);
}
