/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 173447dfff228bd02444e911a7bab46ce10d045fa62952111c704220891c6671
 * Model name: model
 * Graph name: constant_of_shape_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t shape[3] = {
    2LL, 3LL, 4LL
};

/*
 * Node 0:
 * OpType: ConstantOfShape
 * Inputs: shape
 * Outputs: out
 * Attrs:
 *   value: dims: 1
data_type: 1
float_data: 1.25
name: "fill"

 */
static inline void model_op0(const int64_t input0[restrict 3], float output[restrict 2][3][4]) {
    (void)input0;
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            for (size_t i2 = 0; i2 < 4; ++i2) {
                output[i0][i1][i2] = 1.25f;
            }
        }
    }
}

void model(float out[restrict 2][3][4]) {
    model_op0(shape, out);
}
