/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 173447dfff228bd02444e911a7bab46ce10d045fa62952111c704220891c6671
 * Model name: model
 * Graph name: constant_of_shape_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Weight 1:
 * Name: weight1_shape
 * Shape: (3,)
 * Elements: 3
 * Dtype: int64
 */
extern const int64_t weight1_shape[3];

/*
 * Weight 1:
 * Name: weight1_shape
 * Shape: (3,)
 * Elements: 3
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_shape[3] = {
    2LL, 3LL, 4LL
};

/*
 * Node 0:
 * OpType: ConstantOfShape
 * Name: n/a
 * Inputs: shape
 * Outputs: out
 * Attrs:
 *   value: dims: 1
data_type: 1
float_data: 1.25
name: "fill"

 */
static inline void node0_constantofshape(const int64_t input0[3], float output[2][3][4]) {
    (void)input0;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                output[i0][i1][i2] = 1.25f;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(float out[restrict 2][3][4]) {
    node0_constantofshape(weight1_shape, out);
}
