/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 322340c74141029528d668a2025bb60c505d501d3ffdea7315f7b96d80c420ad
 * Model name: model
 * Graph name: cumsum_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Weight 1:
 * Name: weight1_axis
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
static const int64_t weight1_axis[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: CumSum
 * Name: n/a
 * Inputs: input, axis
 * Outputs: output
 * Attrs:
 *   exclusive: 0
 *   reverse: 0
 */
static inline void node0_cumsum(const float input0[restrict 2][3], float output[restrict 2][3]) {
    const size_t dims[2] = { 2, 3 };
    int axis = 1;
    if (axis < 0) {
        axis += 2;
    }
    if (axis < 0 || axis >= 2) {
        return;
    }
    size_t outer = 1;
    for (int i = 0; i < axis; ++i) {
        outer *= dims[i];
    }
    size_t inner = 1;
    for (int i = axis + 1; i < 2; ++i) {
        inner *= dims[i];
    }
    size_t axis_dim = dims[axis];
    for (size_t outer_index = 0; outer_index < outer; ++outer_index) {
        for (size_t inner_index = 0; inner_index < inner; ++inner_index) {
            float acc = (float)0;
            size_t base = (outer_index * axis_dim * inner) + inner_index;
            for (size_t axis_index = 0; axis_index < axis_dim; ++axis_index) {
                size_t offset = base + axis_index * inner;
                acc += input0[offset];
                output[offset] = acc;
            }
        }
    }
}

void model(const float input[restrict 2][3], float output[restrict 2][3]) {
    node0_cumsum(input, output);
}
