/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 0077169ef232cc1c63689c66feb370fdd1ebd9a0fb79c7616c52af22eb4e7920
 * Model name: model
 * Graph name: clip_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

extern const float weight1_min[1];
extern const float weight2_max[1];

/*
 * Weight 1:
 * Name: weight1_min
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
const EMX_UNUSED float weight1_min[1] = {
    0x0.0p+0f
};

/*
 * Weight 2:
 * Name: weight2_max
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
const EMX_UNUSED float weight2_max[1] = {
    0x1.800000p+2f
};

static inline float ref_scalar_f32_fmin(float a, float b) {
    return fminf(a, b);
}

static inline float ref_scalar_f32_fmax(float a, float b) {
    return fmaxf(a, b);
}

/*
 * Node 0:
 * OpType: Clip
 * Name: n/a
 * Inputs: input, min, max
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_clip(const float input0[2][3], const float input_min[1], const float input_max[1], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            float value = input0[i0][i1];
            const float min_value = input_min[0];
            const float max_value = input_max[0];
            value = ref_scalar_f32_fmax(value, min_value);
            value = ref_scalar_f32_fmin(value, max_value);
            output[i0][i1] = value;
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 2][3], float output[restrict 2][3]) {
    node0_clip(input, weight1_min, weight2_max, output);
}
