/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 0ef9243d7d29a136c5888cd57996ea904abfcf4d4d8206676f2ed818ac9630f5
 * Model name: model
 * Graph name: depthtospace_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: DepthToSpace
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   blocksize: 2
 *   mode: DCR
 */
static inline void model_op0(const float in0[restrict 1][4][2][2], float out[restrict 1][1][4][4]) {
    const float *input_data = (const float *)in0;
    float *output_data = (float *)out;
    size_t output_index = 0;
    for (size_t n = 0; n < 1; ++n) {
        for (size_t c_out = 0; c_out < 1; ++c_out) {
            for (size_t h_out = 0; h_out < 4; ++h_out) {
                size_t h_in = h_out / 2;
                size_t offset_h = h_out % 2;
                for (size_t w_out = 0; w_out < 4; ++w_out) {
                    size_t w_in = w_out / 2;
                    size_t offset_w = w_out % 2;
                    size_t c_in;
                    c_in = (offset_h * 2 + offset_w) * 1 + c_out;
                    size_t input_index = ((n * 4 + c_in) * 2 + h_in) * 2 + w_in;
                    output_data[output_index] = input_data[input_index];
                    output_index++;
                }
            }
        }
    }
}

void model(const float in0[restrict 1][4][2][2], float out[restrict 1][1][4][4]) {
    model_op0(in0, out);
}
