/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 799553b323d156380400b5891ca9a17ffd74803c21258ada168d056ea557a499
 * Model name: model
 * Graph name: expand_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

extern const int64_t weight1_shape[2];

/*
 * Weight 1:
 * Name: weight1_shape
 * Shape: (2,)
 * Elements: 2
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_shape[2] = {
    2LL, 3LL
};

/*
 * Node 0:
 * OpType: Expand
 * Name: n/a
 * Inputs: input, shape
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_expand(const float input0[1][3], float output[2][3]) {
    const float *input_data = (const float *)input0;
    float *output_data = (float *)output;
    idx_t output_index = 0;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            idx_t input_index = i1 * 1;
            output_data[output_index] = input_data[input_index];
            output_index++;
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 1][3], float output[restrict 2][3]) {
    node0_expand(input, output);
}
