/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 799553b323d156380400b5891ca9a17ffd74803c21258ada168d056ea557a499
 * Model name: model
 * Graph name: expand_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t shape[2] = {
    2LL, 3LL
};

/*
 * Node 0:
 * OpType: Expand
 * Name: n/a
 * Inputs: input, shape
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_expand(const float input0[restrict 1][3], float output[restrict 2][3]) {
    const float *input_data = (const float *)input0;
    float *output_data = (float *)output;
    size_t output_index = 0;
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            size_t input_index = i1 * 1;
            output_data[output_index] = input_data[input_index];
            output_index++;
        }
    }
}

void model(const float input[restrict 1][3], float output[restrict 2][3]) {
    node0_expand(input, output);
}
