/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): b180e800849ef5619d609858f1b2805972295f4d973ed6c888f5d32aca542794
 * Model name: model
 * Graph name: eye_like_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: EyeLike
 * Name: n/a
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   k: 0
 */
static inline void node0_eyelike(const float input0[restrict 3][3], float output[restrict 3][3]) {
    (void)input0;
    float *output_data = (float *)output;
    idx_t total = (idx_t)1 * 3 * 3;
    for (idx_t index = 0; index < total; ++index) {
        output_data[index] = 0.0f;
    }
    idx_t k = 0;
    idx_t rows = 3;
    idx_t cols = 3;
    idx_t row_start = k >= 0 ? 0 : -k;
    idx_t col_start = k >= 0 ? k : 0;
    if (row_start >= rows || col_start >= cols) {
        return;
    }
    idx_t max_rows = rows - row_start;
    idx_t max_cols = cols - col_start;
    idx_t diag_len = max_rows < max_cols ? max_rows : max_cols;
    for (idx_t batch = 0; batch < 1; ++batch) {
        idx_t base = batch * rows * cols;
        for (idx_t diag = 0; diag < diag_len; ++diag) {
            idx_t row = row_start + diag;
            idx_t col = col_start + diag;
            output_data[base + row * cols + col] = ((float)1);
        }
    }
}

void model(const float input[restrict 3][3], float output[restrict 3][3]) {
    node0_eyelike(input, output);
}
