/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): b180e800849ef5619d609858f1b2805972295f4d973ed6c888f5d32aca542794
 * Model name: model
 * Graph name: eye_like_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: EyeLike
 * Inputs: input
 * Outputs: output
 * Attrs:
 *   k: 0
 */
static inline void model_op0(const float input[restrict 3][3], float output[restrict 3][3]) {
    (void)input;
    float *output_data = (float *)output;
    size_t total = (size_t)1 * 3 * 3;
    for (size_t index = 0; index < total; ++index) {
        output_data[index] = 0.0f;
    }
    int k = 0;
    size_t rows = 3;
    size_t cols = 3;
    size_t row_start = k >= 0 ? 0 : (size_t)(-k);
    size_t col_start = k >= 0 ? (size_t)k : 0;
    if (row_start >= rows || col_start >= cols) {
        return;
    }
    size_t max_rows = rows - row_start;
    size_t max_cols = cols - col_start;
    size_t diag_len = max_rows < max_cols ? max_rows : max_cols;
    for (size_t batch = 0; batch < 1; ++batch) {
        size_t base = batch * rows * cols;
        for (size_t diag = 0; diag < diag_len; ++diag) {
            size_t row = row_start + diag;
            size_t col = col_start + diag;
            output_data[base + row * cols + col] = ((float)1);
        }
    }
}

void model(const float input[restrict 3][3], float output[restrict 3][3]) {
    model_op0(input, output);
}
