/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 21039f2d623a6f163b1fd9396223e81579c7a3f90bb3fb449e5b378aa4813add
 * Model name: model
 * Graph name: gemm_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: Gemm
 * Name: n/a
 * Inputs: in0, in1, in2
 * Outputs: out
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 */
static inline void node0_Gemm(const float input_a[restrict 2][3], const float input_b[restrict 3][4], const float input_c[restrict 2][4], float output[restrict 2][4]) {
    for (size_t i = 0; i < 2; ++i) {
        for (size_t j = 0; j < 4; ++j) {
            float acc = 0.0f;
            for (size_t k = 0; k < 3; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[k][j];
                acc += a_val * b_val;
            }
            size_t c_i = i;
            size_t c_j = j;
            const float bias = input_c[c_i][c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

void model(const float in0[restrict 2][3], const float in1[restrict 3][4], const float in2[restrict 2][4], float out[restrict 2][4]) {
    node0_Gemm(in0, in1, in2, out);
}
