/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 32aaa8c706419e6640e00037e197e205a9465893c5b5e02f6cae6e64c235b02e
 * Model name: model
 * Graph name: gridsample_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=22
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: GridSample
 * Inputs: x, grid
 * Outputs: y
 * Attrs:
 *   align_corners: 0
 *   mode: linear
 *   padding_mode: zeros
 */
static inline double model_op0_reflect(double value, double x_min, double x_max) {
    const double range = x_max - x_min;
    if (range == 0.0) {
        return x_min;
    }
    if (value < x_min) {
        const double dx = x_min - value;
        const int n = (int)(dx / range);
        const double r = dx - (double)n * range;
        return (n % 2 == 0) ? (x_min + r) : (x_max - r);
    }
    if (value > x_max) {
        const double dx = value - x_max;
        const int n = (int)(dx / range);
        const double r = dx - (double)n * range;
        return (n % 2 == 0) ? (x_max - r) : (x_min + r);
    }
    return value;
}

static inline void model_op0(const float x[restrict 1][1][2][2], const float grid[restrict 1][2][2][2], float y[restrict 1][1][2][2]) {
    const int input_spatial[2] = { 2, 2 };
    const double border_min[2] = { -0.5, -0.5 };
    const double border_max[2] = { 1.5, 1.5 };
    for (size_t i0 = 0; i0 < 1; ++i0) {
        for (size_t i1 = 0; i1 < 1; ++i1) {
            for (size_t i2 = 0; i2 < 2; ++i2) {
                for (size_t i3 = 0; i3 < 2; ++i3) {
                    double coords[2];
                    const double grid_0 = (double)grid[i0][i2][i3][1];
                    coords[0] = ((grid_0 + 1.0) * (double)input_spatial[0] - 1.0) / 2.0;
                    const double grid_1 = (double)grid[i0][i2][i3][0];
                    coords[1] = ((grid_1 + 1.0) * (double)input_spatial[1] - 1.0) / 2.0;
                    int base[2];
                    int upper[2];
                    double w0[2];
                    double w1[2];
                    base[0] = (int)floor(coords[0]);
                    upper[0] = base[0] + 1;
                    w1[0] = coords[0] - (double)base[0];
                    w0[0] = 1.0 - w1[0];
                    base[1] = (int)floor(coords[1]);
                    upper[1] = base[1] + 1;
                    w1[1] = coords[1] - (double)base[1];
                    w0[1] = 1.0 - w1[1];
                    double acc = 0.0;
                    {
                        double weight = 1.0;
                        int idx0 = base[0];
                        weight *= w0[0];
                        int idx1 = base[1];
                        weight *= w0[1];
                        int in_bounds = 1;
                        if (idx0 < 0 || idx0 >= input_spatial[0]) {
                            in_bounds = 0;
                        }
                        if (idx1 < 0 || idx1 >= input_spatial[1]) {
                            in_bounds = 0;
                        }
                        if (in_bounds) {
                            acc += weight * (double)x[i0][i1][idx0][idx1];
                        }
                    }
                    {
                        double weight = 1.0;
                        int idx0 = base[0];
                        weight *= w0[0];
                        int idx1 = upper[1];
                        weight *= w1[1];
                        int in_bounds = 1;
                        if (idx0 < 0 || idx0 >= input_spatial[0]) {
                            in_bounds = 0;
                        }
                        if (idx1 < 0 || idx1 >= input_spatial[1]) {
                            in_bounds = 0;
                        }
                        if (in_bounds) {
                            acc += weight * (double)x[i0][i1][idx0][idx1];
                        }
                    }
                    {
                        double weight = 1.0;
                        int idx0 = upper[0];
                        weight *= w1[0];
                        int idx1 = base[1];
                        weight *= w0[1];
                        int in_bounds = 1;
                        if (idx0 < 0 || idx0 >= input_spatial[0]) {
                            in_bounds = 0;
                        }
                        if (idx1 < 0 || idx1 >= input_spatial[1]) {
                            in_bounds = 0;
                        }
                        if (in_bounds) {
                            acc += weight * (double)x[i0][i1][idx0][idx1];
                        }
                    }
                    {
                        double weight = 1.0;
                        int idx0 = upper[0];
                        weight *= w1[0];
                        int idx1 = upper[1];
                        weight *= w1[1];
                        int in_bounds = 1;
                        if (idx0 < 0 || idx0 >= input_spatial[0]) {
                            in_bounds = 0;
                        }
                        if (idx1 < 0 || idx1 >= input_spatial[1]) {
                            in_bounds = 0;
                        }
                        if (in_bounds) {
                            acc += weight * (double)x[i0][i1][idx0][idx1];
                        }
                    }
                    y[i0][i1][i2][i3] = (float)acc;
                }
            }
        }
    }
}

void model(const float x[restrict 1][1][2][2], const float grid[restrict 1][2][2][2], float y[restrict 1][1][2][2]) {
    model_op0(x, grid, y);
}
