/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): cf87587567fd5f6e3189eba635080a0643972872b2cc4da99afd611678c48b3a
 * Model name: model
 * Graph name: groupnormalization_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=21
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: GroupNormalization
 * Inputs: in0, in1, in2
 * Outputs: out
 * Attrs:
 *   epsilon: 9.999999747378752e-06
 *   num_groups: 2
 */
static inline void model_op0(const float input0[restrict 1][4][2][2], const float scale[restrict 4], const float bias[restrict 4], float output[restrict 1][4][2][2]) {
    for (size_t i0 = 0; i0 < 1; ++i0) {
        for (size_t g = 0; g < 2; ++g) {
            float sum = 0.0f;
            for (size_t c_in_group = 0; c_in_group < 2; ++c_in_group) {
                size_t c = g * 2 + c_in_group;
                for (size_t i2 = 0; i2 < 2; ++i2) {
                    for (size_t i3 = 0; i3 < 2; ++i3) {
                        sum += input0[i0][c][i2][i3];
                    }
                }
            }
            float mean = sum / (2 * 4);
            float var = 0.0f;
            for (size_t c_in_group = 0; c_in_group < 2; ++c_in_group) {
                size_t c = g * 2 + c_in_group;
                for (size_t i2 = 0; i2 < 2; ++i2) {
                    for (size_t i3 = 0; i3 < 2; ++i3) {
                        float diff = input0[i0][c][i2][i3] - mean;
                        var += diff * diff;
                    }
                }
            }
            float denom = sqrtf(var / (2 * 4) + 9.99999975e-06f);
            for (size_t c_in_group = 0; c_in_group < 2; ++c_in_group) {
                size_t c = g * 2 + c_in_group;
                for (size_t i2 = 0; i2 < 2; ++i2) {
                    for (size_t i3 = 0; i3 < 2; ++i3) {
                        output[i0][c][i2][i3] =
                        (input0[i0][c][i2][i3] - mean) / denom * scale[c] + bias[c];
                    }
                }
            }
        }
    }
}

void model(const float in0[restrict 1][4][2][2], const float in1[restrict 4], const float in2[restrict 4], float out[restrict 1][4][2][2]) {
    model_op0(in0, in1, in2, out);
}
