/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 133987b9c8aa0107377ca66fb4442465cf2e33cb1444d4ad8a679acca6a2f477
 * Model name: model
 * Graph name: gather_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Node 0:
 * OpType: Gather
 * Name: n/a
 * Inputs: data, indices
 * Outputs: out
 * Attrs:
 *   axis: 0
 */
static inline void node0_gather(const float data[restrict 3][2], const int64_t indices[restrict 2], float output[restrict 2][2]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 2; ++i1) {
            int64_t gather_index = (int64_t)indices[i0];
            if (gather_index < 0) {
                gather_index += 3;
            }
            output[i0][i1] = data[gather_index][i1];
        }
    }
}

void model(const float data[restrict 3][2], const int64_t indices[restrict 2], float out[restrict 2][2]) {
    node0_gather(data, indices, out);
}
