/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 430c455d4232b2dc78d6b0d15d3dd8c1b194e4f2046d3b2265b58d583e5d3aa0
 * Model name: model
 * Graph name: globalmaxpool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: GlobalMaxPool
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_globalmaxpool(const float input0[1][2][4][3], float output[1][2][1][1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 2; ++i1) {
            for (idx_t i2 = 0; i2 < 1; ++i2) {
                for (idx_t i3 = 0; i3 < 1; ++i3) {
                    float acc = -INFINITY;
                    for (idx_t r0 = 0; r0 < 4; ++r0) {
                        for (idx_t r1 = 0; r1 < 3; ++r1) {
                            if (input0[i0][i1][r0][r1] > acc) acc = input0[i0][i1][r0][r1];
                        }
                    }
                    output[i0][i1][i2][i3] = acc;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 1][2][4][3], float out[restrict 1][2][1][1]) {
    node0_globalmaxpool(in0, out);
}
