/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): c0b87c4d4c16ea7d5aeb7b46301552dbb081466d5be1bf2473efd7a84428e7e4
 * Model name: model
 * Graph name: gather_elements_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: GatherElements
 * Name: n/a
 * Inputs: data, indices
 * Outputs: out
 * Attrs:
 *   axis: 0
 */
static inline void node0_gatherelements(const float data[restrict 2][3], const int64_t indices[restrict 2][3], float output[restrict 2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            idx_t gather_index = indices[i0][i1];
            if (gather_index < 0) {
                gather_index += 2;
            }
            output[i0][i1] = data[gather_index][i1];
        }
    }
}

void model(const float data[restrict 2][3], const int64_t indices[restrict 2][3], float out[restrict 2][3]) {
    node0_gatherelements(data, indices, out);
}
