/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 1c61607d379ca1854c7b102c070012bb3eb893305d9b9844eaa05dd231f728e8
 * Model name: model
 * Graph name: hardmax_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_fmax(float a, float b) {
    return fmaxf(a, b);
}

/*
 * Node 0:
 * OpType: Hardmax
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   axis: 1
 */
static inline void node0_hardmax(const float input0[2][3], float output[2][3]) {
    const float *input_flat = (const float *)input0;
    float *output_flat = (float *)output;
    const idx_t outer = 2;
    const idx_t axis_size = 3;
    const idx_t inner = 1;
    for (idx_t outer_idx = 0; outer_idx < outer; ++outer_idx) {
        for (idx_t inner_idx = 0; inner_idx < inner; ++inner_idx) {
            idx_t base = (outer_idx * axis_size * inner) + inner_idx;
            float max_value = input_flat[base];
            idx_t max_index = 0;
            for (idx_t axis_idx = 1; axis_idx < axis_size; ++axis_idx) {
                float value = input_flat[base + axis_idx * inner];
                const float prev_max = max_value;
                max_value = ref_scalar_f32_fmax(max_value, value);
                max_index = (value > prev_max) ? axis_idx : max_index;
            }
            for (idx_t axis_idx = 0; axis_idx < axis_size; ++axis_idx) {
                output_flat[base + axis_idx * inner] =
                axis_idx == max_index ? 1.0f : 0.0f;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_hardmax(in0, out);
}
