/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): bd216e293bfa55e5b3d02f938ffc3e9e800a21c7c7b9e95da4083943be9f4d8b
 * Model name: model
 * Graph name: instancenormalization_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=22
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: InstanceNormalization
 * Name: n/a
 * Inputs: in0, in1, in2
 * Outputs: out
 * Attrs:
 *   epsilon: 9.999999747378752e-06
 */
static inline void node0_InstanceNormalization(const float input0[restrict 1][3][2][2], const float scale[restrict 3], const float bias[restrict 3], float output[restrict 1][3][2][2]) {
    for (size_t i0 = 0; i0 < 1; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            float sum = 0.0f;
            for (size_t i2 = 0; i2 < 2; ++i2) {
                for (size_t i3 = 0; i3 < 2; ++i3) {
                    sum += input0[i0][i1][i2][i3];
                }
            }
            float mean = sum / 4;
            float var = 0.0f;
            for (size_t i2 = 0; i2 < 2; ++i2) {
                for (size_t i3 = 0; i3 < 2; ++i3) {
                    float diff = input0[i0][i1][i2][i3] - mean;
                    var += diff * diff;
                }
            }
            float denom = sqrtf(var / 4 + 9.99999975e-06f);
            for (size_t i2 = 0; i2 < 2; ++i2) {
                for (size_t i3 = 0; i3 < 2; ++i3) {
                    output[i0][i1][i2][i3] =
                    (input0[i0][i1][i2][i3] - mean) / denom * scale[i1] + bias[i1];
                }
            }
        }
    }
}

void model(const float in0[restrict 1][3][2][2], const float in1[restrict 3], const float in2[restrict 3], float out[restrict 1][3][2][2]) {
    node0_InstanceNormalization(in0, in1, in2, out);
}
