/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): d21c265dc7a0bd024135f3f0288c9cef3fa741990037ff30f987cbf194551a87
 * Model name: model
 * Graph name: identity_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <string.h>

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Identity(const float input0[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = input0[i0][i1];
        }
    }
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_Identity(in0, out);
}
