/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): a90898e5c613dc4eaf87571a7f4df3e5486893d30003765a55a36d0ad5b7001c
 * Model name: model
 * Graph name: lrn_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: LRN
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   alpha: 9.999999747378752e-05
 *   beta: 0.75
 *   bias: 1.0
 *   size: 3
 */
static inline void node0_lrn(const float input0[restrict 1][3][4][4], float output[restrict 1][3][4][4]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                for (idx_t i3 = 0; i3 < 4; ++i3) {
                    idx_t channel_start = i1 > 1 ? i1 - 1 : 0;
                    idx_t channel_end = i1 + 1;
                    if (channel_end >= 3) {
                        channel_end = 3 - 1;
                    }
                    float sum = 0.0f;
                    for (idx_t c = channel_start; c <= channel_end; ++c) {
                        float val = input0[i0][c][i2][i3];
                        sum += val * val;
                    }
                    float scale = 1.0f + 3.33333325e-05f * sum;
                    output[i0][i1][i2][i3] = input0[i0][i1][i2][i3] / powf(scale, 0.75f);
                }
            }
        }
    }
}

void model(const float in0[restrict 1][3][4][4], float out[restrict 1][3][4][4]) {
    node0_lrn(in0, out);
}
