/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): e63df4da2c17e33436b6e1ddfbe405bb1e730d145a3a1f2bef2c34133c6943ce
 * Model name: model
 * Graph name: logsoftmax_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_fmax(float a, float b) {
    return fmaxf(a, b);
}

/*
 * Node 0:
 * OpType: LogSoftmax
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   axis: 1
 */
static inline void node0_logsoftmax(const float input0[2][3], float output[2][3]) {
    const float *input_flat = (const float *)input0;
    float *output_flat = (float *)output;
    const idx_t outer = 2;
    const idx_t axis_size = 3;
    const idx_t inner = 1;
    for (idx_t outer_idx = 0; outer_idx < outer; ++outer_idx) {
        for (idx_t inner_idx = 0; inner_idx < inner; ++inner_idx) {
            idx_t base = (outer_idx * axis_size * inner) + inner_idx;
            float max_value = input_flat[base];
            for (idx_t axis_idx = 1; axis_idx < axis_size; ++axis_idx) {
                float value = input_flat[base + axis_idx * inner];
                max_value = ref_scalar_f32_fmax(max_value, value);
            }
            float sum = 0;
            for (idx_t axis_idx = 0; axis_idx < axis_size; ++axis_idx) {
                float value = expf(input_flat[base + axis_idx * inner] - max_value);
                sum += value;
            }
            float logsum = logf(sum);
            for (idx_t axis_idx = 0; axis_idx < axis_size; ++axis_idx) {
                float value = input_flat[base + axis_idx * inner] - max_value;
                output_flat[base + axis_idx * inner] = value - logsum;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_logsoftmax(in0, out);
}
