/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 81dbe123d9cfcb9fa3fef46b8ed462ccf676cbc93fd2a8aa879a41feed63b4c0
 * Model name: model
 * Graph name: lstm_graph
 * Inputs: 3 Outputs: 3 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: LSTM
 * Inputs: X, W, R
 * Outputs: Y, Y_h, Y_c
 * Attrs:
 *   hidden_size: 3
 *   layout: 0
 */

static inline void model_op0(const float X[restrict 1][1][2], const float W[restrict 1][12][2], const float R[restrict 1][12][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3], float Y_c[restrict 1][1][3]) {
    {
        const int dir = 0;
        const int reverse = 0;
        const float alpha_f = 1.0f;
        const float alpha_g = 1.0f;
        const float alpha_h = 1.0f;
        const float beta_f = 0.0f;
        const float beta_g = 0.0f;
        const float beta_h = 0.0f;
        float H_prev[1][3];
        float C_prev[1][3];
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                H_prev[b][h] = 0.0f;
                C_prev[b][h] = 0.0f;
            }
        }
        for (int step = 0; step < 1; ++step) {
            int t = reverse ? (1 - 1 - step) : step;
            for (int b = 0; b < 1; ++b) {
                int seq_limit = 1;
                if (step >= seq_limit) {
                    for (int h = 0; h < 3; ++h) {
                        Y[step][dir][b][h] = 0.0f;
                    }
                    continue;
                }
                float H_next[3];
                float C_next[3];
                for (int h = 0; h < 3; ++h) {
                    float gate_i = 0.0f;
                    float gate_o = 0.0f;
                    float gate_f = 0.0f;
                    float gate_c = 0.0f;
                    for (int i = 0; i < 2; ++i) {
                        float x_val = X[t][b][i];
                        gate_i += x_val * W[dir][h][i];
                        gate_o += x_val * W[dir][3 + h][i];
                        gate_f += x_val * W[dir][3 * 2 + h][i];
                        gate_c += x_val * W[dir][3 * 3 + h][i];
                    }
                    for (int i = 0; i < 3; ++i) {
                        float h_val = H_prev[b][i];
                        gate_i += h_val * R[dir][h][i];
                        gate_o += h_val * R[dir][3 + h][i];
                        gate_f += h_val * R[dir][3 * 2 + h][i];
                        gate_c += h_val * R[dir][3 * 3 + h][i];
                    }
                    float i_gate = gate_i;
                    i_gate = (float)1.0f / ((float)1.0f + expf(-i_gate));

                    float f_gate = gate_f;
                    f_gate = (float)1.0f / ((float)1.0f + expf(-f_gate));

                    float c_gate = gate_c;
                    c_gate = tanhf(c_gate);

                    float c_new = f_gate * C_prev[b][h] + i_gate * c_gate;
                    float o_gate = gate_o;
                    o_gate = (float)1.0f / ((float)1.0f + expf(-o_gate));

                    float h_gate = c_new;
                    h_gate = tanhf(h_gate);

                    float h_new = o_gate * h_gate;
                    C_next[h] = c_new;
                    H_next[h] = h_new;
                    Y[step][dir][b][h] = h_new;
                }
                for (int h = 0; h < 3; ++h) {
                    C_prev[b][h] = C_next[h];
                    H_prev[b][h] = H_next[h];
                }
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                Y_h[dir][b][h] = H_prev[b][h];
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                Y_c[dir][b][h] = C_prev[b][h];
            }
        }
    }
}

void model(const float X[restrict 1][1][2], const float W[restrict 1][12][2], const float R[restrict 1][12][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3], float Y_c[restrict 1][1][3]) {
    model_op0(X, W, R, Y, Y_h, Y_c);
}
