/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 81dbe123d9cfcb9fa3fef46b8ed462ccf676cbc93fd2a8aa879a41feed63b4c0
 * Model name: model
 * Graph name: lstm_graph
 * Inputs: 3 Outputs: 3 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif

static inline float ref_scalar_f32_sigmoid(float a) {
    return 1.0f / (1.0f + expf(-a));
}

static inline float ref_scalar_f32_tanh(float a) {
    return tanhf(a);
}

/*
 * Node 0:
 * OpType: LSTM
 * Name: n/a
 * Inputs: X, W, R
 * Outputs: Y, Y_h, Y_c
 * Attrs:
 *   hidden_size: 3
 *   layout: 0
 */
static inline void node0_lstm(const float input_x[restrict 1][1][2], const float input_w[restrict 1][12][2], const float input_r[restrict 1][12][3], float output_y[restrict 1][1][1][3], float output_y_h[restrict 1][1][3], float output_y_c[restrict 1][1][3]) {
    {
        const int dir = 0;
        const int reverse = 0;
        float H_prev[1][3];
        float C_prev[1][3];
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                H_prev[b][h] = 0.0f;
                C_prev[b][h] = 0.0f;
            }
        }
        for (int b = 0; b < 1; ++b) {
            int seq_limit = 1;
            for (int step = 0; step < seq_limit; ++step) {
                int t = reverse ? (1 - 1 - step) : step;
                float H_next[3];
                float C_next[3];
                for (int h = 0; h < 3; ++h) {
                    float gate_i = 0.0f;
                    float gate_o = 0.0f;
                    float gate_f = 0.0f;
                    float gate_c = 0.0f;
                    for (int i = 0; i < 2; ++i) {
                        float x_val = input_x[t][b][i];
                        gate_i += x_val * input_w[dir][h][i];
                        gate_o += x_val * input_w[dir][3 + h][i];
                        gate_f += x_val * input_w[dir][3 * 2 + h][i];
                        gate_c += x_val * input_w[dir][3 * 3 + h][i];
                    }
                    for (int i = 0; i < 3; ++i) {
                        float h_val = H_prev[b][i];
                        gate_i += h_val * input_r[dir][h][i];
                        gate_o += h_val * input_r[dir][3 + h][i];
                        gate_f += h_val * input_r[dir][3 * 2 + h][i];
                        gate_c += h_val * input_r[dir][3 * 3 + h][i];
                    }
                    float i_gate = ref_scalar_f32_sigmoid(gate_i);
                    float f_gate = ref_scalar_f32_sigmoid(gate_f);
                    float c_gate = ref_scalar_f32_tanh(gate_c);
                    float c_new = f_gate * C_prev[b][h] + i_gate * c_gate;
                    float o_gate = ref_scalar_f32_sigmoid(gate_o);
                    float h_new = o_gate * ref_scalar_f32_tanh(c_new);
                    C_next[h] = c_new;
                    H_next[h] = h_new;
                    output_y[step][dir][b][h] = h_new;
                }
                for (int h = 0; h < 3; ++h) {
                    C_prev[b][h] = C_next[h];
                    H_prev[b][h] = H_next[h];
                }
            }
            for (int step = seq_limit; step < 1; ++step) {
                for (int h = 0; h < 3; ++h) {
                    output_y[step][dir][b][h] = 0.0f;
                }
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                output_y_h[dir][b][h] = H_prev[b][h];
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                output_y_c[dir][b][h] = C_prev[b][h];
            }
        }
    }
}

void model(const float X[restrict 1][1][2], const float W[restrict 1][12][2], const float R[restrict 1][12][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3], float Y_c[restrict 1][1][3]) {
    node0_lstm(X, W, R, Y, Y_h, Y_c);
}
