/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 81dbe123d9cfcb9fa3fef46b8ed462ccf676cbc93fd2a8aa879a41feed63b4c0
 * Model name: model
 * Graph name: lstm_graph
 * Inputs: 3 Outputs: 3 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: LSTM
 * Inputs: X, W, R
 * Outputs: Y, Y_h, Y_c
 * Attrs:
 *   hidden_size: 3
 *   layout: 0
 */
static inline float model_op0_activation(int kind, float value, float alpha, float beta) {
    switch (kind) {
        case 0: /* Relu */
        return value > 0.0f ? value : 0.0f;
        case 1: /* Tanh */
        return tanhf(value);
        case 2: /* Sigmoid */
        return (float)1.0f / ((float)1.0f + expf(-value));
        case 3: /* Affine */
        return alpha * value + beta;
        case 4: /* LeakyRelu */
        return value < 0.0f ? alpha * value : value;
        case 5: /* ThresholdedRelu */
        return value > alpha ? value : 0.0f;
        case 6: /* ScaledTanh */
        return alpha * tanhf(beta * value);
        case 7: /* HardSigmoid */
        value = alpha * value + beta;
        if (value < 0.0f) {
            return 0.0f;
        }
        if (value > (float)1.0f) {
            return (float)1.0f;
        }
        return value;
        case 8: /* Elu */
        return value >= 0.0f ? value : alpha * (expf(value) - (float)1.0f);
        case 9: /* Softsign */
        return value / ((float)1.0f + fabsf(value));
        case 10: /* Softplus */
        return log1pf(expf(value));
        default:
        return value;
    }
}

static inline void model_op0(const float X[restrict 1][1][2], const float W[restrict 1][12][2], const float R[restrict 1][12][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3], float Y_c[restrict 1][1][3]) {
    const int activations[] = { 2, 1, 1 };
    const float activation_alpha[] = { 1.0f, 1.0f, 1.0f };
    const float activation_beta[] = { 0.0f, 0.0f, 0.0f };
    for (int dir = 0; dir < 1; ++dir) {
        int reverse = 0;
        int act_offset = dir * 3;
        int act_f = activations[act_offset];
        int act_g = activations[act_offset + 1];
        int act_h = activations[act_offset + 2];
        float alpha_f = activation_alpha[act_offset];
        float alpha_g = activation_alpha[act_offset + 1];
        float alpha_h = activation_alpha[act_offset + 2];
        float beta_f = activation_beta[act_offset];
        float beta_g = activation_beta[act_offset + 1];
        float beta_h = activation_beta[act_offset + 2];
        float H_prev[1][3];
        float C_prev[1][3];
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                H_prev[b][h] = 0.0f;
                C_prev[b][h] = 0.0f;
            }
        }
        for (int step = 0; step < 1; ++step) {
            int t = reverse ? (1 - 1 - step) : step;
            for (int b = 0; b < 1; ++b) {
                int seq_limit = 1;
                if (step >= seq_limit) {
                    for (int h = 0; h < 3; ++h) {
                        Y[step][dir][b][h] = 0.0f;
                    }
                    continue;
                }
                float H_next[3];
                float C_next[3];
                for (int h = 0; h < 3; ++h) {
                    float gate_i = 0.0f;
                    float gate_o = 0.0f;
                    float gate_f = 0.0f;
                    float gate_c = 0.0f;
                    for (int i = 0; i < 2; ++i) {
                        float x_val = X[t][b][i];
                        gate_i += x_val * W[dir][h][i];
                        gate_o += x_val * W[dir][3 + h][i];
                        gate_f += x_val * W[dir][3 * 2 + h][i];
                        gate_c += x_val * W[dir][3 * 3 + h][i];
                    }
                    for (int i = 0; i < 3; ++i) {
                        float h_val = H_prev[b][i];
                        gate_i += h_val * R[dir][h][i];
                        gate_o += h_val * R[dir][3 + h][i];
                        gate_f += h_val * R[dir][3 * 2 + h][i];
                        gate_c += h_val * R[dir][3 * 3 + h][i];
                    }
                    float i_gate = model_op0_activation(act_f, gate_i, alpha_f, beta_f);
                    float f_gate;
                    f_gate = model_op0_activation(act_f, gate_f, alpha_f, beta_f);
                    float c_gate = model_op0_activation(act_g, gate_c, alpha_g, beta_g);
                    float c_new = f_gate * C_prev[b][h] + i_gate * c_gate;
                    float o_gate = model_op0_activation(act_f, gate_o, alpha_f, beta_f);
                    float h_new = o_gate * model_op0_activation(act_h, c_new, alpha_h, beta_h);
                    C_next[h] = c_new;
                    H_next[h] = h_new;
                    Y[step][dir][b][h] = h_new;
                }
                for (int h = 0; h < 3; ++h) {
                    C_prev[b][h] = C_next[h];
                    H_prev[b][h] = H_next[h];
                }
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                Y_h[dir][b][h] = H_prev[b][h];
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                Y_c[dir][b][h] = C_prev[b][h];
            }
        }
    }
}

void model(const float X[restrict 1][1][2], const float W[restrict 1][12][2], const float R[restrict 1][12][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3], float Y_c[restrict 1][1][3]) {
    model_op0(X, W, R, Y, Y_h, Y_c);
}
