/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): d448a18cd9184a160ffa5fe1e72c2aabdfe216358e8feeec3e163a5ccd01e098
 * Model name: model
 * Graph name: matmul_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: MatMul
 * Name: n/a
 * Inputs: in0, in1
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_MatMul(const float input0[restrict 2][3], const float input1[restrict 3][4], float output[restrict 2][4]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 4; ++i1) {
            float acc = 0.0f;
            for (size_t k = 0; k < 3; ++k) {
                acc += input0[i0][k] * input1[k][i1];
            }
            output[i0][i1] = acc;
        }
    }
}

void model(const float in0[restrict 2][3], const float in1[restrict 3][4], float out[restrict 2][4]) {
    node0_MatMul(in0, in1, out);
}
