/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 82a856077fbf0dd624ed657f1888d1f8475339d8508f049c35b80444baa58e79
 * Model name: model
 * Graph name: meanvariancenormalization_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: MeanVarianceNormalization
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   axes: [-1]
 */
static inline void node0_meanvariancenormalization(const float input0[restrict 2][3][4], float output[restrict 2][3][4]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            float sum = 0.0f;
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                sum += input0[i0][i1][i2];
            }
            float mean = sum / 4;
            float var = 0.0f;
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                float diff = input0[i0][i1][i2] - mean;
                var += diff * diff;
            }
            float denom = sqrtf(var / 4 + 1e-09f);
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                output[i0][i1][i2] = (input0[i0][i1][i2] - mean) / denom;
            }
        }
    }
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][3][4]) {
    node0_meanvariancenormalization(in0, out);
}
