/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 565c69847ccb64227f2e3f3ba14de9bf4db00c488e4bf976b6abc3527d0a935d
 * Model name: model
 * Graph name: maxpool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_fmax(float a, float b) {
    return fmaxf(a, b);
}

/*
 * Node 0:
 * OpType: MaxPool
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   ceil_mode: 0
 *   kernel_shape: [2, 2]
 *   pads: [0, 0, 0, 0]
 *   strides: [2, 2]
 */
static inline void node0_maxpool(const float input0[1][1][4][4], float output[1][1][2][2]) {
    for (idx_t n = 0; n < 1; ++n) {
        for (idx_t c = 0; c < 1; ++c) {
            for (idx_t oh = 0; oh < 2; ++oh) {
                for (idx_t ow = 0; ow < 2; ++ow) {
                    float max_value = -INFINITY;
                    for (idx_t kh = 0; kh < 2; ++kh) {
                        const idx_t ih = oh * 2 + kh * 1 - 0;
                        if (ih >= 0 && ih < 4) {
                            for (idx_t kw = 0; kw < 2; ++kw) {
                                const idx_t iw = ow * 2 + kw * 1 - 0;
                                if (iw >= 0 && iw < 4) {
                                    float val = input0[n][c][ih][iw];
                                    max_value = ref_scalar_f32_fmax(max_value, val);
                                }
                            }
                        }
                    }
                    output[n][c][oh][ow] = max_value;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 1][1][4][4], float out[restrict 1][1][2][2]) {
    node0_maxpool(in0, out);
}
