/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): d474f0cca37070c415fd8cfbe73244ef2f1b5259b88612172579cef0c6deead3
 * Model name: model
 * Graph name: sum_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

/*
 * Node 0:
 * OpType: Sum
 * Name: n/a
 * Inputs: in0, in1, in2
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_sum(const float input0[restrict 2][3], const float input1[restrict 2][3], const float input2[restrict 2][3], float output[restrict 2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = input0[i0][i1];
            output[i0][i1] = ref_scalar_f32_add(output[i0][i1], input1[i0][i1]);
            output[i0][i1] = ref_scalar_f32_add(output[i0][i1], input2[i0][i1]);
        }
    }
}

void model(const float in0[restrict 2][3], const float in1[restrict 2][3], const float in2[restrict 2][3], float out[restrict 2][3]) {
    node0_sum(in0, in1, in2, out);
}
