/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): abce1d43dbc6f2c559be24e9afd29cfa222b9eb03e008e4e5a9cd58866b21125
 * Model name: model
 * Graph name: mish_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_mish(float a) {
    if (a > 20.0f) {
        return a;
    }
    if (a < -20.0f) {
        float exp_a = expf(a);
        return a * exp_a;
    }
    float softplus = log1pf(expf(a));
    return a * tanhf(softplus);
}

/*
 * Node 0:
 * OpType: Mish
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_mish(const float input0[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_mish(input0[i0][i1]);
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_mish(in0, out);
}
