/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 565c69847ccb64227f2e3f3ba14de9bf4db00c488e4bf976b6abc3527d0a935d
 * Model name: model
 * Graph name: maxpool_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: MaxPool
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   ceil_mode: 0
 *   kernel_shape: [2, 2]
 *   pads: [0, 0, 0, 0]
 *   strides: [2, 2]
 */
static inline void node0_maxpool(const float input0[restrict 1][1][4][4], float output[restrict 1][1][2][2]) {
    for (idx_t n = 0; n < 1; ++n) {
        for (idx_t c = 0; c < 1; ++c) {
            for (idx_t oh = 0; oh < 2; ++oh) {
                for (idx_t ow = 0; ow < 2; ++ow) {
                    float max_value = -INFINITY;
                    for (idx_t kh = 0; kh < 2; ++kh) {
                        const int ih = (int)(oh * 2 + kh * 1) - 0;
                        if (ih < 0 || ih >= 4) {
                            continue;
                        }
                        for (idx_t kw = 0; kw < 2; ++kw) {
                            const int iw = (int)(ow * 2 + kw * 1) - 0;
                            if (iw < 0 || iw >= 4) {
                                continue;
                            }
                            float val = input0[n][c][ih][iw];
                            if (val > max_value) {
                                max_value = val;
                            }
                        }
                    }
                    output[n][c][oh][ow] = max_value;
                }
            }
        }
    }
}

void model(const float in0[restrict 1][1][4][4], float out[restrict 1][1][2][2]) {
    node0_maxpool(in0, out);
}
