/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): cd6a52efa394ab06768a8a1d57847b33bd3da1a1046ad1b756724996cd35cf70
 * Model name: model
 * Graph name: nllloss_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: NegativeLogLikelihoodLoss
 * Name: n/a
 * Inputs: input, target
 * Outputs: loss
 * Attrs:
 *   reduction: mean
 */
static inline void node0_negativeloglikelihoodloss(const float input0[restrict 2][3], const int64_t target[restrict 2], float output[restrict 1]) {
    const float *input_flat = (const float *)input0;
    const int64_t *target_flat = (const int64_t *)target;
    float *output_flat = (float *)output;
    const idx_t n = 2;
    const idx_t c = 3;
    const idx_t d = 1;
    float loss_sum = 0.0f;
    float weight_sum = 0.0f;
    for (idx_t n_idx = 0; n_idx < n; ++n_idx) {
        for (idx_t d_idx = 0; d_idx < d; ++d_idx) {
            idx_t target_index = n_idx * d + d_idx;
            int64_t target_value = target_flat[target_index];
            if ((int64_t)target_value == -1) {
                continue;
            }
            idx_t class_index = (idx_t)target_value;
            idx_t input_index = (n_idx * c + class_index) * d + d_idx;
            float value = -input_flat[input_index];
            float sample_weight = 1.0f;
            loss_sum += value;
            weight_sum += sample_weight;
        }
    }
    if (weight_sum == 0.0f) {
        output_flat[0] = 0.0f;
    } else {
        output_flat[0] = loss_sum / weight_sum;
    }
}

void model(const float input[restrict 2][3], const int64_t target[restrict 2], float loss[restrict 1]) {
    node0_negativeloglikelihoodloss(input, target, loss);
}
