/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 01d42bff2a59f2dbaaeb53cdd1cf1c03d39dc8d60272645cfcb2b1c185250285
 * Model name: model
 * Graph name: pad_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Weight 1:
 * Name: pads
 * Shape: (4,)
 * Elements: 4
 * Dtype: int64
 */
static const int64_t pads[4] = {
    0LL, 1LL, 0LL, 1LL
};

/*
 * Weight 2:
 * Name: value
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
static const float value[1] = {
    0.0f
};

/*
 * Node 0:
 * OpType: Pad
 * Name: n/a
 * Inputs: input, pads, value
 * Outputs: output
 * Attrs:
 *   mode: constant
 */
static inline void node0_Pad(const float input[restrict 2][3], float output[restrict 2][5]) {
    const float *input_flat = (const float *)input;
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 5; ++i1) {
            output[i0][i1] = 0.0f;
        }
    }
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 5; ++i1) {
            ptrdiff_t pad_index = 0;
            int pad_in_bounds = 1;
            ptrdiff_t pad_idx0 = (ptrdiff_t)i0 - (ptrdiff_t)(0);
            if (2 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx0 < 0 || pad_idx0 >= (ptrdiff_t)2)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx0 * 3;
            }
            ptrdiff_t pad_idx1 = (ptrdiff_t)i1 - (ptrdiff_t)(1);
            if (3 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx1 < 0 || pad_idx1 >= (ptrdiff_t)3)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx1 * 1;
            }
            if (!pad_in_bounds) {
                continue;
            }
            output[i0][i1] = input_flat[pad_index];
        }
    }
}

void model(const float input[restrict 2][3], float output[restrict 2][5]) {
    node0_Pad(input, output);
}
