/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): b087823f2d63abb3c12849f279cf8e5450c2d994c48572c9ac4a12372a49c1df
 * Model name: model
 * Graph name: reducemean_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Weight 1:
 * Name: weight1_axes
 * Shape: (1,)
 * Elements: 1
 * Dtype: int64
 */
static const EMX_UNUSED int64_t weight1_axes[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: ReduceMean
 * Name: n/a
 * Inputs: in0, axes
 * Outputs: out
 * Attrs:
 *   keepdims: 1
 */
static inline void node0_reducemean(const float input0[2][3][4], float output[2][1][4]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                float acc = 0.0f;
                float acc_comp = 0.0f;
                for (idx_t r0 = 0; r0 < 3; ++r0) {
                    float kahan_value = input0[i0][r0][i2];
                    float kahan_y = kahan_value - acc_comp;
                    float kahan_t = acc + kahan_y;
                    acc_comp = (kahan_t - acc) - kahan_y;
                    acc = kahan_t;
                }
                output[i0][i1][i2] = acc / 3.0f;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][1][4]) {
    node0_reducemean(in0, out);
}
