/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 938c1e16f4b3198de5de30c681a58e664dec09781b2df8da766c647f442b5067
 * Model name: model
 * Graph name: range_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 3
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Weight 1:
 * Name: weight1_start
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
static const int64_t weight1_start[1] = {
    0LL
};

/*
 * Weight 2:
 * Name: weight2_limit
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
static const int64_t weight2_limit[1] = {
    4LL
};

/*
 * Weight 3:
 * Name: weight3_delta
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
static const int64_t weight3_delta[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: Range
 * Name: n/a
 * Inputs: start, limit, delta
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_range(const int64_t start[restrict 1], const int64_t limit[restrict 1], const int64_t delta[restrict 1], int64_t output[restrict 4]) {
    (void)limit;
    const int64_t start_value = start[0];
    const int64_t delta_value = delta[0];
    for (idx_t idx = 0; idx < 4; ++idx) {
        output[idx] = start_value + ((int64_t)idx * delta_value);
    }
}

void model(int64_t output[restrict 4]) {
    node0_range(weight1_start, weight2_limit, weight3_delta, output);
}
