/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 938c1e16f4b3198de5de30c681a58e664dec09781b2df8da766c647f442b5067
 * Model name: model
 * Graph name: range_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 3
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t start[1] = {
    0LL
};

static const int64_t limit[1] = {
    4LL
};

static const int64_t delta[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: Range
 * Name: n/a
 * Inputs: start, limit, delta
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_Range(const int64_t start[restrict 1], const int64_t limit[restrict 1], const int64_t delta[restrict 1], int64_t output[restrict 4]) {
    (void)limit;
    const int64_t start_value = start[0];
    const int64_t delta_value = delta[0];
    for (size_t idx = 0; idx < 4; ++idx) {
        output[idx] = start_value + ((int64_t)idx * delta_value);
    }
}

void model(int64_t output[restrict 4]) {
    node0_Range(start, limit, delta, output);
}
