/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 9754eac43aa405d342edf884c8addaffb10cc16a7c90274578c26168e3cc70d6
 * Model name: model
 * Graph name: reshape_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>
#include <string.h>

static const int64_t shape[2] = {
    0LL, -1LL
};

/*
 * Node 0:
 * OpType: Reshape
 * Inputs: in0, shape
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float in0[restrict 2][3][4], float out[restrict 2][12]) {
    memcpy(out, in0, sizeof(float) * 24);
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][12]) {
    model_op0(in0, out);
}
