/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 9754eac43aa405d342edf884c8addaffb10cc16a7c90274578c26168e3cc70d6
 * Model name: model
 * Graph name: reshape_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

extern const int64_t weight1_shape[2];

/*
 * Weight 1:
 * Name: weight1_shape
 * Shape: (2,)
 * Elements: 2
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_shape[2] = {
    0LL, -1LL
};

/*
 * Node 0:
 * OpType: Reshape
 * Name: n/a
 * Inputs: in0, shape
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_reshape(const float input0[2][3][4], float output[2][12]) {
    const float *input0_data = (const float *)input0;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 12; ++i1) {
            idx_t linear_idx = 0;
            linear_idx = linear_idx * 2 + i0;
            linear_idx = linear_idx * 12 + i1;
            output[i0][i1] = input0_data[linear_idx];
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][12]) {
    node0_reshape(in0, out);
}
