/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): b087823f2d63abb3c12849f279cf8e5450c2d994c48572c9ac4a12372a49c1df
 * Model name: model
 * Graph name: reducemean_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t axes[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: ReduceMean
 * Inputs: in0, axes
 * Outputs: out
 * Attrs:
 *   keepdims: 1
 */
static inline void model_op0(const float input0[restrict 2][3][4], float output[restrict 2][1][4]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 1; ++i1) {
            for (size_t i2 = 0; i2 < 4; ++i2) {
                float acc = 0.0f;
                for (size_t r0 = 0; r0 < 3; ++r0) {
                    acc += input0[i0][r0][i2];
                }
                output[i0][i1][i2] = acc / 3.0f;
            }
        }
    }
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][1][4]) {
    model_op0(in0, out);
}
