/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 2a219566c88665466c6f903676d2cd36ce7d291d64d5f849ef8c19f5eddd1681
 * Model name: model
 * Graph name: rmsnormalization_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=23
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: RMSNormalization
 * Name: n/a
 * Inputs: in0, in1
 * Outputs: out
 * Attrs:
 *   axis: -1
 *   epsilon: 9.999999747378752e-06
 */
static inline void node0_rmsnormalization(const float input0[2][3][4], const float scale[4], float output[2][3][4]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            float sum = 0.0f;
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                float value = input0[i0][i1][i2];
                sum += value * value;
            }
            float mean_square = sum / 4;
            float denom = sqrtf(mean_square + 9.99999975e-06f);
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                float value = input0[i0][i1][i2] / denom;
                value = value * scale[i2];
                output[i0][i1][i2] = value;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3][4], const float in1[restrict 4], float out[restrict 2][3][4]) {
    node0_rmsnormalization(in0, in1, out);
}
