/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): ac5661b2d517bbae7c3d627535134121850108a791f3516ba32ff275b320b50f
 * Model name: model
 * Graph name: shape_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

/*
 * Node 0:
 * OpType: Shape
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Shape(const float input0[restrict 2][3][4], int64_t output[restrict 3]) {
    (void)input0;
    output[0] = 2LL;
    output[1] = 3LL;
    output[2] = 4LL;
}

void model(const float in0[restrict 2][3][4], int64_t out[restrict 3]) {
    node0_Shape(in0, out);
}
