/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): c6fb1a8c689028a6d73eef3115876b0b8387acd86e11ba7e4961f0a9148cdf4c
 * Model name: model
 * Graph name: size_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Node 0:
 * OpType: Size
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_size(const float input0[restrict 2][3][4], int64_t output[restrict 1]) {
    (void)input0;
    output[0] = 24LL;
}

void model(const float in0[restrict 2][3][4], int64_t out[restrict 1]) {
    node0_size(in0, out);
}
