/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): f95eabcda454d5c91f7335ddea2c05b88c3d9d90b682984da011e9558bbb3c97
 * Model name: model
 * Graph name: slice_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 4
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t starts[2] = {
    0LL, 1LL
};

static const int64_t ends[2] = {
    2LL, 3LL
};

static const int64_t axes[2] = {
    0LL, 2LL
};

static const int64_t steps[2] = {
    1LL, 2LL
};

/*
 * Node 0:
 * OpType: Slice
 * Name: n/a
 * Inputs: in0, starts, ends, axes, steps
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Slice(const float input0[restrict 2][3][4], float output[restrict 2][3][1]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            for (size_t i2 = 0; i2 < 1; ++i2) {
                output[i0][i1][i2] = input0[i0][i1][1 + 2 * i2];
            }
        }
    }
}

void model(const float in0[restrict 2][3][4], float out[restrict 2][3][1]) {
    node0_Slice(in0, out);
}
