/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 9f2394718ce05cf614d064eeb6e1e970492240f3cb46f51c1d721609af12efcd
 * Model name: model
 * Graph name: transpose_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: Transpose
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   perm: [2, 0, 1]
 */
static inline void model_op0(const float in0[restrict 2][3][4], float out[restrict 4][2][3]) {
    for (size_t i0 = 0; i0 < 4; ++i0) {
        for (size_t i1 = 0; i1 < 2; ++i1) {
            for (size_t i2 = 0; i2 < 3; ++i2) {
                out[i0][i1][i2] = in0[i1][i2][i0];
            }
        }
    }
}

void model(const float in0[restrict 2][3][4], float out[restrict 4][2][3]) {
    model_op0(in0, out);
}
