/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): 37c3f5bff2beebdceefc2547d6e65e53b35945e1bb253d8b87cc1360b33fada4
 * Model name: model
 * Graph name: tile_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Weight 1:
 * Name: weight1_repeats
 * Shape: (2,)
 * Elements: 2
 * Dtype: int64
 */
static const EMX_UNUSED int64_t weight1_repeats[2] = {
    2LL, 1LL
};

/*
 * Node 0:
 * OpType: Tile
 * Name: n/a
 * Inputs: input, repeats
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_tile(const float input0[2][3], float output[4][3]) {
    const float *input_data = (const float *)input0;
    float *output_data = (float *)output;
    idx_t output_index = 0;
    for (idx_t i0 = 0; i0 < 4; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            idx_t input_index = (i0 % 2) * 3 + (i1 % 3) * 1;
            output_data[output_index] = input_data[input_index];
            output_index++;
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 2][3], float output[restrict 4][3]) {
    node0_tile(input, output);
}
