/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 37c3f5bff2beebdceefc2547d6e65e53b35945e1bb253d8b87cc1360b33fada4
 * Model name: model
 * Graph name: tile_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdint.h>

static const int64_t repeats[2] = {
    2LL, 1LL
};

/*
 * Node 0:
 * OpType: Tile
 * Name: n/a
 * Inputs: input, repeats
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_Tile(const float input0[restrict 2][3], float output[restrict 4][3]) {
    const float *input_data = (const float *)input0;
    float *output_data = (float *)output;
    size_t output_index = 0;
    for (size_t i0 = 0; i0 < 4; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            size_t input_index = (i0 % 2) * 3 + (i1 % 3) * 1;
            output_data[output_index] = input_data[input_index];
            output_index++;
        }
    }
}

void model(const float input[restrict 2][3], float output[restrict 4][3]) {
    node0_Tile(input, output);
}
