/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: n/a
 * Model checksum (sha256): b785032f3c4292b5d82dd6959900411dbda8d0994ccaf8cd1e3ef4979049ff4d
 * Model name: model
 * Graph name: tanh_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

static inline float ref_scalar_f32_tanh(float a) {
    return tanhf(a);
}

/*
 * Node 0:
 * OpType: Tanh
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_tanh(const float input0[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_tanh(input0[i0][i1]);
        }
    }
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_tanh(in0, out);
}
