/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): b7558848b92d9b90edc707d66ae6f3236a37b215ec9aa67f9376408b6b78061c
 * Model name: model
 * Graph name: where_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <stdbool.h>

/*
 * Node 0:
 * OpType: Where
 * Inputs: condition, x, y
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const bool condition[restrict 2][3], const float input_x[restrict 2][3], const float input_y[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = condition[i0][i1] ? input_x[i0][i1] : input_y[i0][i1];
        }
    }
}

void model(const bool condition[restrict 2][3], const float x[restrict 2][3], const float y[restrict 2][3], float out[restrict 2][3]) {
    model_op0(condition, x, y, out);
}
