/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 3a12371987501a27222ed7cf6d31eb6b3d4c3eddeccc5549e02d7c5e054cab5b
 * Model name: model
 * Graph name: relu_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>

/*
 * Node 0:
 * OpType: Relu
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float x[2][3], float out[2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = x[i0][i1] > 0.0f ? x[i0][i1] : 0.0f;
        }
    }
}

void model(const float x[2][3], float out[2][3]) {
    model_op0(x, out);
}
