/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 56e67e71a25b4e264b52f9751a6b7929fdedf329bc0645850ee9c60d3498833e
 * Model name: model
 * Graph name: tanh_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>

/*
 * Node 0:
 * OpType: Tanh
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void model_op0(const float x[restrict 2][3], float out[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = tanhf(x[i0][i1]);
        }
    }
}

void model(const float x[restrict 2][3], float out[restrict 2][3]) {
    model_op0(x, out);
}
