/*
 * Generated by emmtrix ONNX to C Compiler (emx-onnx2c)
 *
 * Command line: n/a
 * Model checksum (sha256): 56e67e71a25b4e264b52f9751a6b7929fdedf329bc0645850ee9c60d3498833e
 * Model name: model
 * Graph name: tanh_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stddef.h>
#include <math.h>
#include <float.h>

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif

static inline float ref_scalar_f32_tanh(float a) {
    return tanhf(a);
}

/*
 * Node 0:
 * OpType: Tanh
 * Name: n/a
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_Tanh(const float input0[restrict 2][3], float output[restrict 2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_tanh(input0[i0][i1]);
        }
    }
}

void model(const float x[restrict 2][3], float out[restrict 2][3]) {
    node0_Tanh(x, out);
}
